name: Infra Pipeline

on:
  push:
    branches:
      - features

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./assignemt1/parent_module

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./assignemt1/parent_module

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./assignemt1/parent_module

      - name: Terraform Apply
        working-directory: ./assignemt1/parent_module
        run: terraform apply -auto-approve
